Repository voxpupuli/json-schema, pull requests merged in 2024-08, with the labels that each got.

#515 Fix caching issues in JSON::Util::URI
  lib/json-schema/util/uri.rb
  lib/json-schema/validator.rb
  test/uri_util_test.rb
Labels: backwards-incompatible

#478 Switch to latest voxpupuli-rubocop
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  json-schema.gemspec
  test/all_of_ref_schema_test.rb
  test/any_of_ref_schema_test.rb
  test/caching_test.rb
  test/common_test_suite_test.rb
  test/custom_format_test.rb
  test/draft1_test.rb
  test/draft2_test.rb
  test/draft3_test.rb
  test/draft4_test.rb
  test/draft6_test.rb
  test/extends_nested_test.rb
  test/files_test.rb
  test/fragment_resolution_test.rb
  test/fragment_validation_with_ref_test.rb
  test/full_validation_test.rb
  test/initialize_data_test.rb
  test/list_option_test.rb
  test/merge_missing_values_test.rb
  test/min_items_test.rb
  test/one_of_test.rb
  test/relative_definition_test.rb
  test/schema_reader_test.rb
  test/schema_validation_test.rb
  test/stringify_test.rb
  test/support/enum_validation.rb
  test/support/strict_validation.rb
  test/support/test_helper.rb
  test/support/type_validation.rb
  test/type_attribute_test.rb
  test/uri_parsing_test.rb
  test/uri_util_test.rb
  test/validator_schema_reader_test.rb
Labels: enhancement

#526 Release 5.0.0
  CHANGELOG.md
  json-schema.gemspec
Labels: skip-changelog
