Repository voxpupuli/json-schema, pull requests merged in 2025-08, with the labels that each got.

#546 CI: Mark release gem group as optional & please yaml linter for github workflows & configure minimal github token permissions
  .github/workflows/test.yml
  Gemfile
Labels: skip-changelog

#545 Improve :failed_attribute value for custom formats
  lib/json-schema/attributes/formats/custom.rb
  test/custom_format_test.rb
Labels: Bug

#549 Require Ruby 3.2 or newer
  .github/workflows/test.yml
  .rubocop.yml
  .rubocop_todo.yml
  Rakefile
  json-schema.gemspec
  lib/json-schema/attributes/additionalproperties.rb
  lib/json-schema/attributes/allof.rb
  lib/json-schema/attributes/anyof.rb
  lib/json-schema/attributes/extends.rb
  lib/json-schema/attributes/formats/custom.rb
  lib/json-schema/attributes/formats/ip.rb
  lib/json-schema/attributes/oneof.rb
  lib/json-schema/attributes/ref.rb
  lib/json-schema/attributes/required.rb
  lib/json-schema/attributes/type.rb
  lib/json-schema/attributes/type_v4.rb
  lib/json-schema/errors/validation_error.rb
  lib/json-schema/schema.rb
  lib/json-schema/schema/reader.rb
  lib/json-schema/util/array_set.rb
  lib/json-schema/util/uri.rb
  lib/json-schema/util/uuid.rb
  lib/json-schema/validator.rb
  test/custom_format_test.rb
  test/draft4_test.rb
  test/schema_validation_test.rb
Labels: backwards-incompatible
